mod config;
mod display;
mod logger;
mod parse;
mod run;

use crate::display::{Display, DisplayType};
use crate::run::run;

fn main() {
    match run(None, None) {
        Ok(res) => {
            let display = Display::new("Generated by ptest", res);

            display.display(DisplayType::Linear);
        }
        Err(err) => println!("{}", err),
    }
}

#[cfg(test)]
mod tests {
    mod tests;
    mod tests2;
}
